#######################
# Theme Customization #
#######################

title: "kelvin.__init__()"                          # used in <title> tag & site header
author: Kelvin Lee                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Making sense of data with uncertainty.
slogan: ""        # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/sma.jpg                    # used as background in site header
url: https://laserkelvin.github.io              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/laserkelvin   # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg  # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg
  - name: GitHub
    url: https://github.com/laserkelvin
    icon: /i/icons.svg
    outbound: true      # this key sets a link to open in a new window.
  - name: About me
    url: /about
    icon: /i/icons.svg

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Machine Learning in Spectroscopy
    teaser: Using neural networks and Bayesian statistics to solve spectroscopic problems.
    role: Lead
    category: Machine learning
  - title: Bayesian Analysis of Low-Cost Electronic Structure Calculations
    teaser: Probabilistic modeling of uncertainties in spectroscopic constants.
    role: Lead
    category: Bayesian modeling
  - title: Open-source Analysis Tools for Spectroscopy
    teaser: Object-oriented library PySpecTools written in Python 3.7
    url: https://github.com/laserkelvin/PySpecTools
    role: Developer
    category: Python
  - title: Aromatic Chemistry in Space
    teaser: Studying the physics and chemistry of aromatic molecules in space with the Green Bank Telescope.
    url: https://greenbankobservatory.org/science/gbt-surveys/gotham-survey/
    role: Laboratory Experiments & Electronic Structure
    category: Astrochemistry
  - title: Gas-Phase Mechanisms for Molecule Formation
    teaser: Spectroscopic investigations into how molecules form in the gas-phase.
    url: https://pubs.rsc.org/en/content/articlelanding/2019/cp/c8cp06070c#!divAbstract
    role: Laboratory Experiments & Electronic Structure
    category: Astrochemistry
  - title: Exotic Molecules in the Interstellar Medium
    url: https://arxiv.org/abs/1811.12798
    teaser: Searches for transient molecules that reveal new chemical aspects of interstellar space.
    role: Laboratory Experiments & Electronic Structure
    category: Astrochemistry
  - title: Grow of Carbon Chains
    url: https://pubs.rsc.org/en/content/articlelanding/2019/CP/C9CP03607E#!divAbstract
    teaser: Understanding how carbon chains grow in length in the gas-phase.
    role: Lead
    category: Chemistry


#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
