#######################
# Theme Customization #
#######################

title: laserkelvin                          # used in <title> tag & site header
author: Kelvin Lee                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Making sense of data with uncertainty.
slogan:                                    # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue'' # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/laserkelvin
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: kin.long.kelvin.lee       # you know, to protect you from bots. (handle and domain
    domain: gmail.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Machine Learning in Spectroscopy
    teaser: Using neural networks and Bayesian statistics to solve spectroscopic problems.
    role: Lead
    category: Chemistry
  - title: Aromatic Chemistry in Space
    teaser: Studying the physics and chemistry of aromatic molecules in space with the Green Bank Telescope
    url: https://greenbankobservatory.org/science/gbt-surveys/gotham-survey/
    role: Laboratory & Electronic Structure
    category: Observing
  - title: Rihanna
    teaser: Possibly another robot. Also available on Google Play.
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Contributor
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
